project:
  type: website
  resources:
    - resume.pdf
    - CNAME

website:
  title: "Raymond Parcon"
  site-url: https://rayparcon.com
  description: "Genetics of Plant Diseases"
  navbar:
    title: "Raymond Parcon"
    left:
      - href: index.qmd
        text: Bio
      - href: papers
        text: Papers
      - href: presentations
        text: Presentations
      - href: blog.qmd
        text: Blog
  page-footer:
    border: false
    background: light
    center: >-
      <div class="footer-block">
        <div class="footer-links">
          <a href="mailto:rhparcon@uga.edu" title="Email"><i class="fa-solid fa-envelope"></i></a>
          <a href="https://orcid.org/0000-0002-3379-3698" title="ORCID" target="_blank" rel="noopener"><i class="ai ai-orcid"></i></a>
          <a href="https://scholar.google.com/citations?user=zDKlF7kAAAAJ&hl=en" title="Google Scholar" target="_blank" rel="noopener"><i class="ai ai-google-scholar"></i></a>
          <a href="https://github.com/rayparcon" title="GitHub" target="_blank" rel="noopener"><i class="fa-brands fa-github"></i></a>
          <a href="https://www.linkedin.com/in/rayparcon" title="LinkedIn" target="_blank" rel="noopener"><i class="fa-brands fa-linkedin"></i></a>
          <a href="https://www.instagram.com/ry.parcs/" title="Instagram" target="_blank" rel="noopener"><i class="fa-brands fa-instagram"></i></a>
          <a href="resume.pdf" title="Curriculum Vitae"><i class="fa-regular fa-file-pdf"></i></a>
        </div>
        <div class="footer-copyright">
          Website by <a href="https://quarto.org/">Quarto</a> © 2026 Raymond Parcon 
          <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">CC BY-NC-SA 4.0</a>
        </div>
      </div>

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: false



