project:
  type: website
  resources:
    - resume.pdf
    - CNAME

website:
  title: "Raymond Parcon"
  site-url: https://rayparcon.com
  description: "Genetics of Plant Diseases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: presentations
        text: Presentations
      - href: blog.qmd
        text: Blog
  page-footer:
    center: Website by [Quarto](https://quarto.org/) © 2026 Raymond Parcon [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: false



